config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # Authentication
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    get "/logout" => "sessions#destroy", :as => :logout
    get "/signup" => "registrations#new", :as => :signup
    scope "my" do
      get "profile", to: "registrations#edit"
      put "profile/update", to: "registrations#update"
    end
  end

  authenticated :user do
    resources :dashboard, only: [:index] do
      collection do
        get :home
      end
    end
  end

  unauthenticated do
    as :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :dashboard do
    collection do
      get :about
    end
  end

  resources :contacts
  resources :merchants do 
    collection { post :import }
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"

    namespace :admin do
      resources :users
      resources :todos
      root to: "users#index"
    end
  end

  resources :todos do
    post 'comments', to: "comments#create"
    delete :delete_image_attachment, on: :member
  end
  root to: "todos#new"

  namespace :api do
    namespace :v1 do 
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "logout", to: "sessions#logout"
      end
      
      # Todos
      resources :todos, only: [:index, :create, :destroy, :update, :show]

      #Merchants
      resources :merchants, only: [:create] do 
        collection { post :import }
      end
    end
  end
  # root to: "dashboard#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/header/_boostrap_flash.html.erb
<% flash.each do |name, message| %>
  <% if message.present? %>
    <% alert_class = name.to_s == 'alert' ? "danger" : "success" %>
    <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
      <div class="container">
        <a class="close" data-dismiss="alert"> ×</a>
        <%= content_tag :div, message, id: "flash_#{name}" if message.is_a?(String) %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/header/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href=<%=image_path "brand/favicon/apple-icon-57x57.png"%>>
<link rel="apple-touch-icon" sizes="60x60" href=<%=image_path "brand/favicon/apple-icon-60x60.png"%> >
<link rel="apple-touch-icon" sizes="72x72"  href=<%=image_path "brand/favicon/apple-icon-72x72.png"%>>
<link rel="apple-touch-icon" sizes="76x76" href=<%=image_path "brand/favicon/apple-icon-76x76.png"%> >
<link rel="apple-touch-icon" sizes="114x114" href=<%=image_path "brand/favicon/apple-icon-114x114.png"%> >
<link rel="apple-touch-icon" sizes="120x120" href=<%=image_path "brand/favicon/apple-icon-120x120.png"%>>
<link rel="apple-touch-icon" sizes="144x144" href=<%=image_path "brand/favicon/apple-icon-144x144.png"%>>
<link rel="apple-touch-icon" sizes="152x152" href=<%=image_path "brand/favicon/apple-icon-152x152.png"%>
<link rel="apple-touch-icon" sizes="180x180" href=<%=image_path "brand/favicon/apple-icon-180x180.png"%>
<link rel="icon" type="image/png" sizes="192x192"  href=<%=image_path "brand/favicon/android-icon-192x192.png"%>>
<link rel="icon" type="image/png" sizes="32x32" href=<%= image_path "brand/favicon/favicon-32x32.png" %>>
<link rel="icon" type="image/png" sizes="96x96" href=<%= image_path "brand/favicon/favicon-96x96.png" %>>
<link rel="icon" type="image/png" sizes="16x16" href=<%= image_path "brand/favicon/favicon-16x16.png" %>>
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" href=<%= image_path "brand/favicon/ms-icon-144x144.png" %>>
<meta name="theme-color" content="#ffffff">

app/views/shared/header/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <%= link_to "Home", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-primary">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <%= link_to root_path do %>
              <%image_tag "brand/brand-text.png"%>
            <%end %>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-primary" aria-controls="navbar-primary" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>

      <ul class="navbar-nav ml-lg-auto">
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="<%=about_dashboard_index_path %>">
            <i class="fas fa-info-circle"></i>
            <span class="nav-link-inner--text d-lg-none">About</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-icon" href="<%=new_contact_path %>">
            <i class="fas fa-comments"></i>
            <span class="nav-link-inner--text d-lg-none">Contact</span>
          </a>
        </li>
        <%=render "shared/header/signed_in_nav" %>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/header/_signed_in_nav.html.erb
<% if user_signed_in? %>
  <li class="nav-item dropdown">
    <a class="nav-link nav-link-icon" href="#" id="navbar-primary_dropdown_1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <i class="fas fa-cog"></i>
      <span class="nav-link-inner--text d-lg-none">Settings</span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-primary_dropdown_1">
      <div class="dropdown-item"><%= current_user.name %></div>
      <%= link_to "My Account", profile_path, class: "dropdown-item" %>
      <% if current_user.admin? %>
        <%= link_to "Admin", admin_root_path, class: "dropdown-item" %>
      <% end %>
      <div class="dropdown-divider"></div>
      <%= link_to "Sign Out", destroy_user_session_path, class: "dropdown-item", method: :delete %>
    </div>
  </li>
<% end %>