config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  # Authentication
  devise_scope :user do
    get "/login" => "devise/sessions#new", as: :login
    get "/logout" => "sessions#destroy", :as => :logout
    get "/signup" => "registrations#new", :as => :signup
    scope "my" do
      get "profile", to: "registrations#edit"
      put "profile/update", to: "registrations#update"
    end
  end

  authenticated :user do
    resources :dashboard, only: [:index] do
      collection do
        get :home
      end
    end
  end

  unauthenticated do
    as :user do
      root to: "devise/sessions#new", as: :unauthenticated_root
    end
  end

  resources :dashboard do
    collection do
      get :about
    end
  end

  resources :contacts
  resources :merchants do 
    collection { post :import }
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"

    namespace :admin do
      resources :users
      resources :todos
      root to: "users#index"
    end
  end

  resources :todos do
    post 'comments', to: "comments#create"
    delete :delete_image_attachment, on: :member
  end
  root to: "todos#new"

  namespace :api do
    namespace :v1 do 
      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        delete "logout", to: "sessions#logout"
      end
      
      # Todos
      resources :todos, only: [:index, :create, :destroy, :update, :show]

      #Merchants
      resources :merchants, only: [:create] do 
        collection { post :import }
      end
    end
  end
  # root to: "dashboard#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord  
  #Association
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :files, dependent: :destroy

  #Validation
  validates :title, presence: true

  validates :status, inclusion: { in: ['not-started', 'in-progress', 'complete'] }

  STATUS_OPTIONS = [
    ['Not started', 'not-started'],
    ['In progress', 'in-progress'],
    ['Complete', 'complete']
  ]

  def readable_status
    case status
    when 'not-started'
      'Not started'
    when 'in-progress'
      'In progress'
    when 'complete'
      'Complete'
    end
  end

  def color_class
    case status
    when 'not-started'
      'primary'
    when 'in-progress'
      'info'
    when 'complete'
      'success'
    end
  end

end

app/controllers/admin/todos_controller.rb
# frozen_string_literal: true

module Admin
  class TodosController < Admin::ApplicationController
  end
end

app/controllers/api/v1/todos_controller.rb
# frozen_string_literal: true

class Api::V1::TodosController < Api::V1::AuthenticatedController
  before_action :set_todo, only: [:update, :destroy, :show]


  # GET  /api/v1/todos
  def index
    begin
      todos = @current_user.
                todos.
                order('created_at DESC').
                paginate(page: params[:page], per_page: 10) 
    rescue => e 
      render_exception(e, 422) && return
    end
    json_response(TodoSerializer.new(todos).serializable_hash[:data].map {|todo| todo[:attributes]},MetaGenerator.new.generate!(todos))
  end

  #POST /api/v1/todos
  def create
    begin
      todo = @current_user.todos.create!(todo_params)
    rescue => e 
      render_exception(e, 422) && return
    end
    json_response(TodoSerializer.new(todo).serializable_hash[:data][:attributes])
  end

  #PUT /api/v1/todos/:id
  def update
    begin
      @todo.update!(todo_params)  
    rescue => e 
      render_exception(e, 422) && return
    end
    json_response(TodoSerializer.new(@todo).serializable_hash[:data][:attributes])
  end

  #GET /api/v1/todos/:id
  def show
    begin
      @todo
    rescue => e 
      render_exception(e, 422) && return
    end
    json_response(TodoSerializer.new(@todo).serializable_hash[:data][:attributes])
  end

  #DELETE /api/v1/todos/:id
  def destroy
    begin
      @todo.destroy
    rescue => e 
      render_exception(e, 422) && return
    end
    render json: { success: true, data: {}, errors: [] }, status: 200
  end

  #private methods
  private

  def todo_params
    params.require(:todo).permit(:title, :desc, :status, :user_id, :due_date, files: [])
  end
  
  def set_todo
    @todo = Todo.find(params[:id])
  end
end 

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  before_action :set_todolist, only: %i[ update new destroy ]
  before_action :authenticate_user!

  # GET /todos or /todos.json
  def index
    redirect_to :action => 'new'
  end

  # GET /todos/1 or /todos/1.json
  def show
    @comment = Comment.new
    @comments = @todo.comments.order("created_at DESC")
  end

  # GET /todos/new
  def new
    @todo =  current_user.todos.build
    @comment = Comment.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = current_user.todos.build(todo_params)
    respond_to do |format|
      if @todo.save
        format.js
      else
        format.js { redirect_back fallback_location: root_path, alert: "#{@todo.errors.full_messages.to_sentence}" }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    redirect_to :action => 'new' if @todo.update(todo_params)
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.js
    end
  end

  #delete Attached Image
  def delete_image_attachment
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    if !attachment.destroyed?
      redirect_back fallback_location: root_path, alert: "Attachment was not destroyed."
    else
      redirect_back fallback_location: root_path, notice: "Attachment destroyed successfully."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :desc, :status, :user_id, :due_date, files: [])
    end

    def set_todolist
      @todo_all = current_user.todos.all
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_delete_file.html.erb
<% todo.files.each do |file|%>
  <% if file.variable? %>
    <%= link_to image_tag(file.variant(resize: "100x100")), file %>
  <% elsif file.previewable? %>
    <%= link_to image_tag(file.preview(resize: "100x100")), rails_blob_path(file, disposition: :attachment)%>
  <% elsif file.image? %>
      <%= link_to image_tag(file, width:100), file %>
  <% else %>
      <%= link_to file.filename, rails_blob_path(file, disposition: :attachment) %>    
  <% end %>
  <%= link_to 'Remove', delete_image_attachment_todo_path(file),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/todos/_delete_list.html.erb
<% @todo_all.each do |todo| %>
  <%= render 'todo_list', todo: todo %>
<% end %>

app/views/todos/_dropdown_status.html.erb
<% if todo.persisted? %>
  <div class="dropdown float-left">
    <button class="btn btn-sm mr-1 btn-outline-<%= todo.color_class %> dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= todo.readable_status %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
      <% Todo::STATUS_OPTIONS.each do |status| %>
        <a class="dropdown-item" href="#"
        data-reflex="click->StatusReflex#change"
        data-id="<%= todo.id %>"
        data-status="<%= status[1] %>">
          <%= status[0] %>
        </a>
      <% end %>
    </div>
  </div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, html: {class: "todolistform"}) do |form| %>
  <div id="todolist_todoid_<%= todo.id%>" class="bg-white border border-blue">
    <div class="d-flex px-3 justify-content-between">
      <div class="m-2">
        <%= form.text_field :title, class: "form-control", placeholder: "Enter Task Name" %>
      </div>
      <div class="m-2">
        <%= form.date_field :due_date, class: 'form-control' %>
      </div>
      <div class="m-2">
        <%= form.file_field :files, multiple: true %>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <%= form.submit class: "btn btn-success m-2"%>
      </div>
    </div>
  </div>
<% end %>

app/views/todos/_todo_list.html.erb
<% @comment_counts = todo.comments.count %>
<% if !todo.due_date.present? %>
  <div id="todolist_todoid_<%= todo.id%>" class="second bg-white border border-blue">
    <div class="d-flex px-3 justify-content-between">
      <div class="m-2">
        <%= link_to edit_todo_path(todo) do %>
          <h3><%= todo.title %></h3>
          <%= render(ProgressBadgeComponent.new(status: todo.status)) %>
        <% end %>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <div class="m-2">
          <%= link_to todo_path(todo) do %>
            <i id="comment_list" class="fas fa-comments"></i> 
            <span><%= @comment_counts%> </span>
            <% end %>
        </div>
      <div>
        <%= render partial: 'dropdown_status', locals: { todo: todo } %>
      </div>
      <div>
        <span class="badge badge-pill badge-primary mt-1 py-2"><%= todo.due_date%></span>
      </div>
        <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "btn btn-danger m-2"%>
      </div>
    </div>
  </div>
  <%= render partial: 'delete_file', locals: { todo: todo } %>
<% elsif todo.due_date <= Date.today %>
  <div class="second bg-white border border-blue">
    <div class="d-flex px-3 justify-content-between">
      <div class="m-2">
        <h3><%= todo.title %></h3>  
        <%= render(ProgressBadgeComponent.new(status: todo.status)) %>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <div class="m-2">
          <%= link_to todo_path(todo) do %>
            <i id="comment_list" class="fas fa-comments"></i> 
            <span><%= @comment_counts%> </span>
          <% end %>
        </div>
        <div>
          <span class="badge badge-pill badge-danger mt-1 py-2"><%= todo.due_date%></span>
        </div>
        <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "btn btn-danger m-2"%>
      </div>
    </div>
  </div>
  <%= render partial: 'delete_file', locals: { todo: todo } %>
<% else %>
  <div id="todolist_todoid_<%= todo.id%>" class="second bg-white border border-blue">
    <div class="d-flex px-3 justify-content-between">
      <div class="m-2">
        <%= link_to edit_todo_path(todo) do %>
          <h3><%= todo.title %></h3>
          <%= render(ProgressBadgeComponent.new(status: todo.status)) %>
        <% end %>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <div class="m-2">
          <%= link_to todo_path(todo) do %>
            <i id="comment_list" class="fas fa-comments"></i> 
            <span><%= @comment_counts%> </span>
          <% end %>
        </div>
        <div>
          <%= render partial: 'dropdown_status', locals: { todo: todo } %>
        </div>
        <div>
          <span class="badge badge-pill badge-primary mt-1 py-2"><%= todo.due_date%></span>
        </div>
        <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: "btn btn-danger m-2"%>
      </div>
    </div>
  </div>
  <%= render partial: 'delete_file', locals: { todo: todo } %>
<% end %>

app/views/todos/create.js.erb
$('#todolist_index').prepend("<%= j render 'todo_list', todo: @todo %>");
$('#todo_title').val('');

app/views/todos/destroy.js.erb
$('#todolist_index').html("<%= j render 'delete_list', todo: @todo_all%>");

app/views/todos/edit.html.erb
<div class="d-flex px-3 mt-3 justify-content-between">
  <h2>Update Todo</h2>
  <%= link_to 'Back', todos_path, class: "btn btn-warning mb-2" %>
</div>
<%= render 'form', todo: @todo %>

app/views/todos/new.html.erb
<h3>Task Managment</h3>
<%= form_with(model: @todo) do |form| %>
  <div class="card">
    <div class="card-body ">
      <div class="form-inline justify-content-md-center">
        <div class="form-group mx-sm-3 mb-2">
          <%= form.text_field :title, class: "form-control", placeholder: "Enter Task Name" %>
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <%= form.date_field :due_date, id: :task_due_date, class: 'form-control' %>
        </div>
        <div class="form-group mx-sm-3 mb-2">
          <%= form.file_field :files, multiple: true %>
        </div>
        <%= form.hidden_field :status, value: 'not-started' %>
        <%= form.submit class:"btn btn-primary mb-2" %>
      </div>
    </div>
  </div>
  <div class="mt-2 container">
    <div id="todolist_index">
      <% @todo_all.each do |todo| %>
        <%= render 'todo_list', todo: todo %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/todos/show.html.erb
<div class="d-flex px-3 mt-3 justify-content-between">
  <h2><%= @todo.title %></h2>
  <%= link_to 'Back', todos_path, class: "btn btn-warning mb-2" %>
</div>
<%= form_with(model: [@todo, @comment]) do |f| %>
  <div class="bg-white border border-blue">
    <div class="d-flex px-3 justify-content-between">
      <div class="w-100 m-2">
        <%= f.text_field :body, class: "form-control", placeholder: "Enter Comment" %>
      </div>
      <div class="form-inline my-2 my-lg-0">
        <%= f.submit "Add Comment", class: "btn btn-success m-2"%>
      </div>
    </div>
  </div>
<% end %>

<div id="comment_all">
  <% @comment_counts = @todo.comments.count %>
  <div class="container">
    <div class="be-comment-block mt-3 border rounded border-blue">
      <h1 class="comments-title">Comments <%= @comment_counts%></h1>
      <% @comments.each do |comment| %>
        <%= render 'comments/comment', comment: comment %>
      <% end %>
    </div>
  </div>
</div>